### ISSUE TITLE
Support valueFrom in the Configuration CRD

### ISSUE THREAD

**Issue by gambol99** [appvia/terraform-controller#30]
At present all the variables supplied to the terraform module are defined in `spec.varaibles` of the Configuration CRD. Where required we could support the a `spec.valueFrom` list i.e. 

```yaml
spec:
  valueFrom: 
    - name: secret 
      key: hello.world
      path: <where we inject into the variables i.e. database.password>
      optional: true|false
```

We have to consider also people changing the secret into between a plan and apply
